# Generated by Django 5.0.1 on 2026-02-21 20:06

from django.db import migrations

def seed_data(apps, schema_editor):
    Exercise = apps.get_model('workouts', 'Exercise')
    IntensityMethod = apps.get_model('workouts', 'IntensityMethod')

    exercises = [
        {'name': 'Bench Press', 'muscle_group': 'Chest'},
        {'name': 'Squat', 'muscle_group': 'Legs'},
        {'name': 'Deadlift', 'muscle_group': 'Back'},
        {'name': 'Overhead Press', 'muscle_group': 'Shoulders'},
        {'name': 'Barbell Row', 'muscle_group': 'Back'},
        {'name': 'Pull Up', 'muscle_group': 'Back'},
        {'name': 'Dumbbell Curl', 'muscle_group': 'Arms'},
        {'name': 'Tricep Extension', 'muscle_group': 'Arms'},
        {'name': 'Leg Press', 'muscle_group': 'Legs'},
        {'name': 'Calf Raise', 'muscle_group': 'Legs'},
    ]
    for ex in exercises:
        Exercise.objects.create(**ex)

    methods = [
        {'name': 'Standard', 'description': 'Standard straight set'},
        {'name': 'Drop Set', 'description': 'Perform a set to failure, then reduce weight and continue'},
        {'name': 'Rest-Pause', 'description': 'Perform a set to failure, rest briefly, then perform more reps'},
        {'name': 'Myo-Reps', 'description': 'Activation set followed by short rest and mini-sets'},
        {'name': 'Superset', 'description': 'Two exercises performed back-to-back with no rest'},
    ]
    for method in methods:
        IntensityMethod.objects.create(**method)

class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
